Add method to turn on/off CUO's follow behavior
jsebold666/RazorEnhanced pull request #134
Opened 2024-03-17 04:30 UTC by sayotte

Have verified in-game that this works, as called by the Python API.

2024-03-17 04:33 UTC, sayotte commented on Razor/RazorEnhanced/CUO.cs
> +            // FIXME this seems important but VisualStudio is throwing errors
I'd genuinely like to get this fixed before any merging happens.

2024-03-19 22:10 UTC, sayotte commented on Razor/RazorEnhanced/CUO.cs
> +            // FIXME this seems important but VisualStudio is throwing errors
This has been fixed.

2024-03-21 18:29 UTC, credzba requested changes
I didn't test it, but I'd avoid throw as it will crash the python script.

2024-03-21 18:29 UTC, credzba commented on Razor/RazorEnhanced/CUO.cs
> +                throw new Exception("No such property 'Scenes' of Game object");
maybe not a throw, how about a message and return nulls as you did if it is OSI client

2024-03-21 18:29 UTC, credzba commented on Razor/RazorEnhanced/CUO.cs
> +                throw new Exception("Scenes property of Game object is null");
same comment. throw would crash the script,

2024-03-23 13:12 UTC, sayotte commented on Razor/RazorEnhanced/CUO.cs
> +                throw new Exception("No such property 'Scenes' of Game object");
@credzba if this breaks, it means the targeted code over in CUO has changed and this API is now broken.

You're saying it's better to print something and proceed with unexpected behavior, than to break and force it to be addressed?

2024-03-23 15:38 UTC, cesare-montresor commented
Absolutely! To exception should ever reach the user. Instead a message
explaining the issues.
People never put try catch in the python scripts

Il sab 23 mar 2024, 14:12 sayotte ***@***.***> ha scritto:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Razor/RazorEnhanced/CUO.cs
> <https://github.com/RazorEnhanced/RazorEnhanced/pull/134#discussion_r1536631398>
> :
>
> > +                throw new Exception("Game property of Client object is null");
> +            }
> +
> +            // From Game, get Scene
> +            PropertyInfo piScene = null;
> +            foreach (var prop in game.GetType().GetProperties())
> +            {
> +                if (prop.Name == "Scene")
> +                {
> +                    piScene = prop;
> +                    break;
> +                }
> +            }
> +            if (piScene == null)
> +            {
> +                throw new Exception("No such property 'Scenes' of Game object");
>
> @credzba <https://github.com/credzba> if this breaks, it means the
> targeted code over in CUO has changed and this API is now broken.
>
> You're saying it's better to print something and proceed with unexpected
> behavior, than to break and force it to be addressed?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RazorEnhanced/RazorEnhanced/pull/134#discussion_r1536631398>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADNK3KISSCNKE6F2CYOQA3YZV5TXAVCNFSM6AAAAABEZ4JRR2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJWGM3TQMZUGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-03-27 19:49 UTC, sayotte commented on Razor/RazorEnhanced/CUO.cs
> +                throw new Exception("No such property 'Scenes' of Game object");
@credzba I've pushed a commit addressing the exception-throwing.

2024-03-29 12:48 UTC, lyncher48 commented
I can't wait this!!!

2024-04-01 03:38 UTC, credzba approved these changes

2024-04-01 03:38 UTC, merged