Detailed buffs
jsebold666/RazorEnhanced pull request #158
Opened 2024-10-05 21:30 UTC by LasherasGH

Hi,

I'm implemented a new version for more detailed Buff data. I tried to do my best to respect the coding style and the old behavior, also threadsafe locks. It gives the feature to get all detailed data about buffs like Title/Description and it arguments (like +15% HCI bonus) to parse it for handle on some script logic, enemy of one target, poison dmg incoming, strangle dmg incoming, etc...

Greetings.

2024-10-06 12:28 UTC, credzba requested changes
add check for packet length at each field you extract past the original bytes.
answer my question about unicodestringle

2024-10-06 12:28 UTC, credzba commented on Razor/Network/Handlers.cs
> +                            p.ReadUInt16(); //null data
You should check that the imcoming buffer is long enough to contain this data.
On some older servers, its possible not all the fields were sent

2024-10-06 12:28 UTC, credzba commented on Razor/Network/Packet.cs
> +            while ((c = ReadByte() | (ReadByte() << 8)) != 0)
This doesn't seem right, if the byte is 0 read another byte and shift left 8 (which for a byte wipes it out ?
copilot suggests:
```
    public string ReadUnicodeStringLE()
    {
        StringBuilder sb = new StringBuilder();
        char c;

        while ((c = _reader.ReadChar()) != '\0')
        {
            sb.Append(c);
        }

        return sb.ToString();
    }
```

2024-10-06 12:34 UTC, LasherasGH commented on Razor/Network/Handlers.cs
> +                            p.ReadUInt16(); //null data
I checked all Read things on packet always check the size its enough thats why skip to recheck it

2024-10-06 12:58 UTC, LasherasGH commented on Razor/Network/Packet.cs
> +            while ((c = ReadByte() | (ReadByte() << 8)) != 0)
humm? i'm so sorry i can't see any object called _reader or ReadChar on this project.  

About the shift, sorry but i don't understand what exactly you mean, it swaps the order because its unicode little endian order, i checked and the packet always come with both bytes filled even if it's null, remember all shifts convert result in to int value, so, if packet with 0x00 + 0x46 come and the second byte its 0x46 it will be 0x4600 unicode result and will be a "F" string value.

Anyways that already exists on Packet object but with more checks, i don't added size checks because ReadByte already do it.

Packet object code:

```

		public string ReadUnicodeStringLE()
		{
			StringBuilder sb = new StringBuilder();

			int c;

			while ((m_Index + 1) < m_Size && (c = (m_Data[m_Index++] | (m_Data[m_Index++] << 8))) != 0)
			{
				sb.Append((char)c);
			}

			return sb.ToString();
		}


```

Of course feel free to change it as you wish :D.

Thanks for your time.

Greetings.

2024-10-06 13:02 UTC, LasherasGH commented
Confirm and tell me if you want me to put the checks on Handler and PacketReader :)

2024-10-10 12:48 UTC, credzba commented on Razor/Network/Handlers.cs
> +                            p.ReadUInt16(); //null data
I didn't go look at Read, if it cant read data, what does it return ? 
because you keep right on using the data

2024-10-10 19:47 UTC, LasherasGH commented on Razor/Network/Handlers.cs
> +                            p.ReadUInt16(); //null data
it returns 0 on numeric types, and string empy for string ones

2024-10-24 04:44 UTC, credzba approved these changes

2024-10-24 04:44 UTC, merged