reopen last pull request with merge to the last update from official and removed some unnecesary files
jsebold666/RazorEnhanced pull request #81
Opened 2022-12-23 09:28 UTC by pkrion

2022-12-23 19:45 UTC, credzba requested changes
I dont understand what your trying to accomplish, and I dont like reflection code spead all over, why doesnt it just stay in CUO,cs ?

2022-12-23 19:45 UTC, credzba commented on Razor/Core/Commands.cs
> +            if (script == null)
This needs to just go into PlayScript, no need for a new function. 
Also, it needs to check for all the suffixes possible.

2022-12-23 19:45 UTC, credzba commented on Razor/Core/Commands.cs
> +                if (text[0] == '<'|| text[0] == '>')
why do we need 3 ways to invoke a script ?

2022-12-23 20:49 UTC, pkrion commented on Razor/Core/Commands.cs
> +            if (script == null)
i dont wanna be invasive, for that i made a new function because is a new command.

2022-12-23 20:50 UTC, pkrion commented on Razor/Core/Commands.cs
> +                if (text[0] == '<'|| text[0] == '>')
cuo uses >macro if you create and ingame macro to play a "RazorMacro"

2022-12-23 20:55 UTC, pkrion commented
respect a reflection files is like a toolbox for futures updates, at this way is easy to solve some of them, in this case, with the first commit about macro command compatibility we add this

[](https://gyazo.com/a0246e79a44cd227db07f9048e6f5a46)

2023-04-16 20:08 UTC, credzba commented
I dunno if this is still needed, but its 6 months old so I am gonna close it

2023-04-16 20:08 UTC, closed without merging